# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  commitHashLength: 2
  nerdFontsVersion: "3"
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
  branchColorPatterns:
    "^feat/": "blue"
    "^fix/": "yellow"
    "^refactor/": "magenta"
    '^\w+-\d+': "green" # '<any-text>-<some-number>' like foo-123
os:
  editPreset: "nvim-remote"
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --syntax-theme base16 --line-numbers
  overrideGpg: true
